/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddressForm: typeof import('./src/components/AddressForm.vue')['default']
    PaymentForm: typeof import('./src/components/PaymentForm.vue')['default']
    PersonalDataForm: typeof import('./src/components/PersonalDataForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
